### ISSUE TITLE
Migration to AsciiDoc: Set up initial document structure

### ISSUE THREAD

**Issue by max-rosin** [OpenSimulationInterface/open-simulation-interface#494]
### Context

Set up the initial structure of the new documentation website, based on AsciiDoc.
This issue is part of resolving #449.

### Goals

- Create initial outline of documentation to enable discussion.
- Create files to enable migration of CI to AsciiDoc early.

### Tasks

- [x] Create document map.
- [x] Create initial document structure (files with headings only, include in map).
- [x] Fill topics with blind text.

**Comment by stefancyliax** [comment]
This is done. Ticket closed.
